### ISSUE TITLE
autoHighlight not working unless match is beginning of an item

### ISSUE THREAD

**Issue by epegzz** [reactjs/react-autocomplete#309] opened 2018-01-31 18:19 UTC
Let's say you have the following items: `Foo`, `Bar`

If you start typing `F` then `Foo` will automatically be highlighted.

But if you instead start typing `o` then `Foo` will not be highlighted.
Therefore, hitting Enter will not select the first item in the second scenario.

**Comment by CMTegner** [comment] 2018-02-04 11:37
Duplicate of #239.

**Closed by CMTegner** 2018-02-04 11:37 UTC
